### ISSUE TITLE
Including example of regsecret.yaml

### ISSUE THREAD

**Issue by IskprinterGitBot** [sdaschner/tekton-argocd-example#1]
Thanks for making this example repo! 

One thing I didn't see is the file `regsecret.yaml` that's mentioned in the readme. I think it would look like this. It would be nice to include it, possibly only in the readme.
```yaml
# regsecret.yaml

apiVersion: v1
   kind: Secret
   metadata:
     name: regsecret
     annotations:
       tekton.dev/docker-0: https://gcr.io
   type: kubernetes.io/basic-auth
   stringData:
     username: <username>
     password: <access-token>
```
